name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Linting ausführen
      - name: Run ESLint
        run: npm run lint

      # 5️⃣ Tests ausführen (falls eingerichtet)
      - name: Run tests
        run: npm test
        continue-on-error: true # Falls du noch keine Tests hast, verhindert das einen Build-Abbruch

      # 6️⃣ Build ausführen
      - name: Build project
        run: npm run build

      # 7️⃣ Build-Artefakte hochladen (optional)
      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist